name: amlv2-dp-png2json
channels:
- conda-forge
dependencies:
- pip
- python=3.8
- pip:
  - azureml-core
  - azureml-dataprep
  - azureml-dataset-runtime[pandas,fuse]
  - azureml-telemetry
  - azure-ai-formrecognizer
  - numpy
  - pandas
  - python-dotenv