name: amlv2-dp-pdf2png
channels:
- conda-forge
dependencies:
- pip
- poppler
- python=3.8
- pip:
  - azureml-core
  - azureml-dataprep
  - azureml-dataset-runtime[pandas,fuse]
  - azureml-telemetry
  - pandas
  - numpy
  - pdf2image